[book]
authors = ["Martin Sehnoutka"]
language = "en"
multilingual = false
src = "src"
title = "OSBuild guides"

[output.html]
site-url = "https://www.osbuild.org/guides/"

[preprocessor.plantuml]
plantuml-cmd="plantuml"
